"""
Exercise 1: Workflow vs. Agent
================================
Domain 1 (Agents and Workflows) - Skill: Agent Architecture (4.5%)

RUNS FREE ON A TEAM/ENTERPRISE (OR PRO/MAX) SUBSCRIPTION
-----------------------------------------------------------
This exercise is built on the **Claude Agent SDK** (`claude-agent-sdk` on
PyPI), not the raw `anthropic` Messages API package. The Agent SDK
authenticates against a Claude.ai subscription via `CLAUDE_CODE_OAUTH_TOKEN`
(generated by running `claude setup-token` once) instead of a metered
Console API key, so if you have a Team, Enterprise, Pro, or Max
subscription, running this costs you nothing beyond your normal usage
limits. See `00-setup/README.md` section 1 for the one-time setup
(`claude setup-token`, exporting the token, installing `claude-agent-sdk`).

This is also more exam-accurate than the raw-API version this exercise used
to be: the blueprint's "Agent Construction with Claude" skill (section 2 of
this domain's README) explicitly names "the Claude Agent SDK" as tested
content, so building the tool-use loop through it - rather than hand-rolling
it - is the thing you're actually expected to know for this skill. (You
still get the hand-rolled version, deliberately, in Exercise 2 - see that
file's docstring for why.)

A note on API currency: the Agent SDK is actively evolving. The specific
functions/classes used below (`query`, `ClaudeAgentOptions`, `tool`,
`create_sdk_mcp_server`) reflect the author's best knowledge as of when this
was written - cross-check exact signatures against code.claude.com if
anything here doesn't behave as described.

THE TASK
--------
You are given three short pieces of customer feedback text. For each one you
need to:
  1. Extract structured data: {"sentiment": "positive"|"negative"|"neutral",
     "topic": <short string>, "needs_human_review": true|false}
  2. A text "needs human review" if it mentions anything related to safety,
     legal threats, or a request to delete the user's account/data.

You will implement this TWICE:

  PART A - AS A WORKFLOW (fixed code path)
    Your Python code calls Claude in a fixed sequence for each text: one
    one-shot `query()` call to extract sentiment+topic, then your own Python
    `if`/`in` logic decides needs_human_review by checking for keywords, OR
    a second fixed one-shot `query()` call that just answers "does this need
    review, yes/no". Claude never decides *how many times* it gets called or
    *what order* - your code does. This is Workflow architecture: LLM calls
    are steps inside logic you wrote. Using the Agent SDK's `query()` here
    doesn't change that - `query()` is just how you're making the call; the
    control flow around it is still 100% yours.

  PART B - AS A SIMPLE AGENT (tool-use loop)
    You give Claude ONE custom tool: `flag_for_review(text_id, reason)`,
    defined with the SDK's `@tool` decorator and exposed to Claude through an
    in-process MCP server (`create_sdk_mcp_server`). You give Claude all
    three texts in a single prompt and tell it: "for each text, decide
    whether it needs human review, and if so call flag_for_review. When
    you've considered all three, reply with a final summary and stop."
    Claude decides, per text, whether to call the tool at all, and Claude
    decides when the task is complete (no more tool calls, just a final text
    answer). Your code doesn't hard-code the review decision anywhere - it
    lives in the model's judgment, exercised through the loop.

    Notice what's DIFFERENT from a hand-rolled loop (Exercise 2): you never
    inspect `stop_reason`, never manually build `tool_result` blocks, never
    write a `while`/`for` loop that calls the API again. The Agent SDK does
    all of that internally - you just declare the tool, hand `query()` a
    prompt, and consume the resulting stream of messages. The workflow/agent
    line (who decides the FLAGGING logic and step sequence) is identical to
    before; what's changed is that a production-grade harness, not your own
    `while` loop, is now running the mechanics.

WHAT YOU SHOULD OBSERVE / HOW TO KNOW YOU SUCCEEDED
----------------------------------------------------
- Part A always makes the same fixed number of Claude calls per text (1 or 2,
  depending on how you structured it) - runs are structurally identical
  every time, even though the *content* of Claude's answers varies.
- Part B makes a *variable* number of tool calls - zero, one, two, or three
  flag_for_review calls depending on what Claude decides about these
  particular texts. Try changing SAMPLE_TEXTS and notice Part B adapts
  automatically (different texts get flagged), while Part A's code doesn't
  need to change at all, it's the same fixed pipeline for any input.
- You should be able to articulate, in your own words (see the ANSWER
  prompt at the bottom), a case where you'd actually prefer Part A's
  approach in production and a case where you'd prefer Part B's - this is
  the "decision criteria" the exam blueprint calls out for Agent Architecture.

NO CREDENTIALS SET UP YET? You can still do this exercise: read through the
TODOs, write the code as best you can, and then manually predict what Claude
would extract and whether it would flag each SAMPLE_TEXTS entry for review.
Write your predictions as comments. The reasoning is the point.
"""

import asyncio
import json

from claude_agent_sdk import (
    AssistantMessage,
    ClaudeAgentOptions,
    TextBlock,
    create_sdk_mcp_server,
    query,
    tool,
)

SAMPLE_TEXTS = [
    {
        "id": "t1",
        "text": (
            "The app crashed twice today while I was checking out. Pretty "
            "annoying but I still like the product overall."
        ),
    },
    {
        "id": "t2",
        "text": (
            "I want every last bit of my data deleted from your systems "
            "immediately, and I'm going to talk to a lawyer about how you "
            "handled my last order."
        ),
    },
    {
        "id": "t3",
        "text": (
            "Great customer support call yesterday, the rep fixed my "
            "billing issue in five minutes."
        ),
    },
]


# ---------------------------------------------------------------------------
# Small shared helper: run a single one-shot query() call and collect its
# final text. You'll use this for every Part A call - it's the Agent-SDK
# equivalent of "one client.messages.create() call, take the text back out".
# ---------------------------------------------------------------------------

async def ask_claude(prompt: str, system_prompt: str | None = None) -> str:
    """
    TODO(shared helper): Build a `ClaudeAgentOptions` (pass `system_prompt=`
    if one was given). Then:

        chunks = []
        async for message in query(prompt=prompt, options=options):
            if isinstance(message, AssistantMessage):
                for block in message.content:
                    if isinstance(block, TextBlock):
                        chunks.append(block.text)
        return "".join(chunks).strip()

    This is a plain one-shot call - no tools involved - so `query()` will
    make exactly one round trip to Claude and yield the result as a stream
    of messages ending with an AssistantMessage containing the answer.
    """
    raise NotImplementedError("TODO: implement ask_claude")


# ---------------------------------------------------------------------------
# PART A: WORKFLOW (fixed sequential query() calls, decision logic in Python)
# ---------------------------------------------------------------------------

async def extract_structured_data(text: str) -> dict:
    """
    TODO(Part A, step 1): Call `ask_claude()` with a prompt that asks Claude
    to return ONLY a JSON object like:
        {"sentiment": "positive"|"negative"|"neutral", "topic": "<short topic>"}
    Parse the JSON out of the response text and return it as a dict.

    Hint: ask explicitly for "respond with ONLY valid JSON, no other text"
    and wrap the parse in a try/except so a malformed response doesn't crash
    the whole workflow - that's exactly the kind of deterministic error
    handling a workflow's fixed code path gives you "for free".
    """
    raise NotImplementedError("TODO: implement extract_structured_data")


def needs_human_review_workflow(text: str) -> bool:
    """
    TODO(Part A, step 2): Decide needs_human_review WITHOUT letting Claude
    control the control flow. Two acceptable approaches - pick one:

      (a) Pure Python keyword check (no extra API call at all): look for
          substrings/keywords like "lawyer", "legal", "delete my data",
          "unsafe", "sue", etc. This is the most "workflow" version -
          zero extra LLM calls, fully deterministic, fully auditable.

      (b) A second, narrowly-scoped `ask_claude()` call that ONLY answers a
          yes/no classification question ("Does this text mention safety
          concerns, legal threats, or a request to delete account/data?
          Answer with exactly YES or NO.") - still a workflow, because YOUR
          code decides this call happens for every single text, always, in
          this fixed position in the pipeline. Claude's unpredictability is
          confined to the content of one yes/no answer, not to
          whether/when it's asked. (If you pick this option, make the
          function `async` and `await ask_claude(...)`.)

    Return True/False.
    """
    raise NotImplementedError("TODO: implement needs_human_review_workflow")


async def run_workflow(samples: list[dict]) -> list[dict]:
    """Fixed pipeline: for every sample, always extract, then always check
    review status, in that order, every time. No sample can skip a step and
    no sample can trigger an extra step. This IS the workflow - regardless
    of whether the underlying call is `client.messages.create()` or
    `query()`, the thing that makes it a workflow is that YOUR code, not
    Claude, decides this sequence happens for every sample."""
    results = []
    for sample in samples:
        data = await extract_structured_data(sample["text"])
        data["id"] = sample["id"]
        data["needs_human_review"] = needs_human_review_workflow(sample["text"])
        results.append(data)
    return results


# ---------------------------------------------------------------------------
# PART B: AGENT (Claude drives a tool-use loop and decides when to flag)
# ---------------------------------------------------------------------------

FLAGGED: list[dict] = []


# TODO(Part B, step 1): Decorate this with @tool(name, description, schema).
# The schema is a dict mapping each input's name to its Python type, e.g.
# {"text_id": str, "reason": str} - the SDK turns this into the JSON schema
# Claude actually sees. The description is what Claude uses to decide WHEN
# to call this tool, so be specific (mirror FLAG_TOOL's old description:
# "call this only for feedback mentioning safety concerns, legal threats, or
# account/data deletion requests").
async def flag_for_review(args):
    """
    TODO(Part B, step 1, continued): The function body. `args` is a dict
    with the keys you declared in the schema (e.g. args["text_id"],
    args["reason"]). Append {"id": args["text_id"], "reason": args["reason"]}
    to FLAGGED (so we can inspect what the agent decided), then return a
    tool result in the SDK's expected shape:
        {"content": [{"type": "text", "text": f"Flagged {args['text_id']} ..."}]}
    """
    raise NotImplementedError("TODO: implement flag_for_review")


async def run_agent(samples: list[dict]) -> str:
    """
    TODO(Part B, step 2): Implement the agent call.

    1. Build one prompt containing ALL THREE texts (with their ids) and
       instructions: "For each text, decide whether it needs human review
       (safety concerns, legal threats, or account/data deletion requests).
       Call flag_for_review for each one that does. When you have
       considered all three texts, respond with a short final summary and
       do not call any more tools."
    2. Wrap your @tool-decorated flag_for_review in an MCP server:
           review_server = create_sdk_mcp_server(
               name="review", version="1.0.0", tools=[flag_for_review]
           )
    3. Build options exposing that tool:
           options = ClaudeAgentOptions(
               mcp_servers={"review": review_server},
               allowed_tools=["mcp__review__flag_for_review"],
               permission_mode="acceptEdits",  # verify current mode names
           )
       (Tool names the SDK exposes to Claude follow the pattern
       mcp__<server_name>__<tool_name> - that's why allowed_tools looks
       like that.)
    4. `async for message in query(prompt=user_prompt, options=options):` -
       collect text from AssistantMessage/TextBlock the same way
       `ask_claude()` does, and return the joined final text.

       Notice you never see a raw tool_use/tool_result block here, never
       check a stop_reason, and never write your own retry loop: the SDK
       runs the entire "Claude asks for a tool -> we run it -> feed the
       result back -> ask again" cycle internally, driven by whatever
       `permission_mode`/`allowed_tools` you configured. Your job was just
       to declare the tool and hand it a prompt - contrast this with
       Exercise 2, where you build that exact cycle by hand.

    Compare: FLAGGED is populated only for texts Claude itself chose to
    flag - contrast with Part A where needs_human_review is computed for
    every single text unconditionally by your fixed code.
    """
    raise NotImplementedError("TODO: implement run_agent")


async def main():
    print("=== PART A: WORKFLOW ===")
    try:
        workflow_results = await run_workflow(SAMPLE_TEXTS)
        print(json.dumps(workflow_results, indent=2))
    except NotImplementedError as e:
        print(f"(not implemented yet: {e})")

    print("\n=== PART B: AGENT ===")
    try:
        summary = await run_agent(SAMPLE_TEXTS)
        print("Agent summary:", summary)
        print("Flagged by the agent:", json.dumps(FLAGGED, indent=2))
    except NotImplementedError as e:
        print(f"(not implemented yet: {e})")

    print(
        "\n=== ANSWER (fill in, 3-5 sentences) ===\n"
        "In your own words: for THIS task (three short feedback texts, "
        "simple review-flagging), which approach would you actually deploy "
        "in production, and why? Then describe one different task where "
        "you'd flip your answer - i.e. a task simple/bounded enough that "
        "the agent's flexibility is a waste of cost and unpredictability, "
        "or conversely a task open-ended enough that hard-coding the steps "
        "would be impossible or brittle."
    )


if __name__ == "__main__":
    asyncio.run(main())
