"""
Exercise 1: Tool Design and Error Handling
============================================
Domain 8 (Tools and MCPs) - Skill: Tool Implementation (4.4%)

THIS VERSION RUNS FREE UNDER A CLAUDE.AI SUBSCRIPTION
-------------------------------------------------------
This exercise uses the **Claude Agent SDK** (`claude_agent_sdk`), not the raw
`anthropic` Messages API package. The Agent SDK (like Claude Code itself) can
authenticate with `CLAUDE_CODE_OAUTH_TOKEN` - a token generated by `claude
setup-token` against your Claude.ai subscription (Pro/Max/Team/Enterprise) -
instead of a metered `ANTHROPIC_API_KEY`. If you have a Team/Enterprise seat,
this exercise costs you nothing beyond your normal subscription usage. See
`00-setup/README.md` section 1 if you haven't set that token up yet.

(It will also work with `ANTHROPIC_API_KEY` set instead, billed through the
metered Console - the SDK doesn't care which credential it finds, see
00-setup/README.md's precedence note. The point of rewriting this exercise
was to make the subscription path available, not to forbid the other one.)

INSTALL: pip install claude-agent-sdk

SDK CURRENCY WARNING: the Claude Agent SDK is actively evolving. The imports,
decorator shape, and message types below are correct as of this writing, but
verify against [code.claude.com](https://code.claude.com) before you build
anything beyond this exercise on top of them - exact names are exactly the
kind of detail that drifts.

THE TASK
--------
You run a tiny mock warehouse system. You will define and wire up THREE
tools for Claude to use against it, this time as an **SDK MCP server** - a
small in-process MCP server the Agent SDK spins up for you, rather than a
list of raw JSON tool schemas passed straight to `client.messages.create`:

  1. lookup_inventory(sku: str) -> how many units of a SKU are in stock
  2. create_order(sku: str, quantity: int, customer_email: str) -> place an
     order, decrementing stock
  3. get_order_status(order_id: str) -> look up a previously created order

The mock backend (MOCK_INVENTORY / MOCK_ORDERS / the three "backend"
functions below) is already implemented for you and deliberately RAISES
PYTHON EXCEPTIONS in a few realistic situations (unknown SKU, insufficient
stock, unknown order id). Your job is everything around it:

  PART A - WRITE THE TOOLS
    Fill in each `@tool(...)` call's name/description/input-schema, and each
    handler's body, so that:
      - Claude can reliably choose the right tool and fill in valid
        arguments without ever seeing the Python implementation. Follow the
        tool description best practices from README.md section 1.3: say
        what the tool does, when to use it, document every parameter, and
        prefer a fixed set of values (an `enum`-shaped constraint) wherever
        one applies.
      - CRITICALLY: each handler calls the matching mock backend function
        inside a try/except. On success, it returns a normal SDK tool
        result: `{"content": [{"type": "text", "text": ...}]}`. On a caught
        InventoryError, it DOES NOT let the exception propagate - instead it
        returns `{"content": [{"type": "text", "text": "Error: ..."}],
        "is_error": True}` (see README.md 1.4 - the SDK MCP tool result
        convention for signaling failure mirrors the raw Messages API's
        `tool_result` / `is_error` shape almost exactly, which is exactly
        the point: the concept travels even though the harness changed).

  PART B - WIRE UP THE SDK MCP SERVER AND RUN A QUERY
    Implement `run_agent(user_message)`:
      - Bundle the three tools into an SDK MCP server with
        `create_sdk_mcp_server(...)`.
      - Build a `ClaudeAgentOptions(mcp_servers=..., allowed_tools=...)` -
        note tool names inside `allowed_tools` follow the
        `mcp__<server_name>__<tool_name>` pattern.
      - Call `query(prompt=user_message, options=options)` and iterate the
        async message stream, capturing the final assistant text.
    Notice what you are NOT writing anymore: there's no hand-rolled `while
    stop_reason == "tool_use"` loop, no manually appending `tool_use` /
    `tool_result` blocks to a `messages` list. The Agent SDK's `query()` runs
    that dispatch loop internally - README.md 1.5 calls this "using a
    harness that's already built" as opposed to hand-writing the loop
    yourself. You still fully own tool *design* (Part A) and error handling
    (still Part A, just living inside the tool handler instead of a
    separate dispatch function) - the SDK only takes the mechanical loop off
    your hands.

  PART C - OBSERVE CLAUDE REACTING TO AN ERROR
    Run the three SCENARIOS at the bottom. At least one of them (ordering
    more units than are in stock) is designed to trigger a backend error.
    Read Claude's final answer for that scenario: a correctly-implemented
    tool handler lets Claude see the structured error and respond sensibly
    (e.g. explain the problem, suggest a smaller quantity, ask what to do
    next) INSTEAD OF your Python process crashing with an uncaught
    exception.

NO CREDENTIALS AT ALL? You can still do this exercise: write the tool
definitions and `run_agent` as best you can (it will read/parse correctly
even if you can't run it), then read through backend_create_order's logic
and manually predict, for each scenario, (a) which tool(s) Claude would
call, (b) whether the mock backend would raise, and (c) what a reasonable
final answer from Claude would look like given the tool result you
constructed. Write your predictions as comments above each scenario.
"""

import asyncio
import json

from claude_agent_sdk import (
    AssistantMessage,
    ClaudeAgentOptions,
    TextBlock,
    create_sdk_mcp_server,
    query,
    tool,
)


# ---------------------------------------------------------------------------
# MOCK BACKEND (already implemented - do not need to change this section)
# ---------------------------------------------------------------------------

MOCK_INVENTORY = {
    "SKU-100": 42,   # widgets
    "SKU-200": 3,    # gadgets (low stock, good for testing insufficient-stock)
    "SKU-300": 0,    # gizmos (out of stock)
}

MOCK_ORDERS = {}
_next_order_id = 1000


class InventoryError(Exception):
    """Raised by the mock backend for any inventory/order problem."""


def backend_lookup_inventory(sku: str) -> int:
    if sku not in MOCK_INVENTORY:
        raise InventoryError(f"Unknown SKU '{sku}'. No such item in inventory.")
    return MOCK_INVENTORY[sku]


def backend_create_order(sku: str, quantity: int, customer_email: str) -> dict:
    global _next_order_id

    if sku not in MOCK_INVENTORY:
        raise InventoryError(f"Unknown SKU '{sku}'. No such item in inventory.")
    if quantity <= 0:
        raise InventoryError("Quantity must be a positive integer.")
    available = MOCK_INVENTORY[sku]
    if quantity > available:
        raise InventoryError(
            f"Insufficient stock for '{sku}': requested {quantity}, "
            f"only {available} available."
        )

    MOCK_INVENTORY[sku] -= quantity
    order_id = f"ORD-{_next_order_id}"
    _next_order_id += 1
    MOCK_ORDERS[order_id] = {
        "order_id": order_id,
        "sku": sku,
        "quantity": quantity,
        "customer_email": customer_email,
        "status": "confirmed",
    }
    return MOCK_ORDERS[order_id]


def backend_get_order_status(order_id: str) -> dict:
    if order_id not in MOCK_ORDERS:
        raise InventoryError(f"Unknown order id '{order_id}'.")
    return MOCK_ORDERS[order_id]


# ---------------------------------------------------------------------------
# PART A: TOOLS (schema + handler + error handling, all in one place)
# ---------------------------------------------------------------------------
#
# The @tool decorator takes (name, description, input_schema_dict). The
# input_schema_dict maps parameter name -> Python type (str, int, float,
# bool...) - the SDK builds the JSON Schema for you from that, which is why
# the description still has to carry everything a plain type annotation
# can't: format, units, what a valid value looks like, when to call this
# tool at all. Same principle as README.md 1.3, just a terser schema shape.

@tool(
    "lookup_inventory",
    "TODO",  # TODO: what does it do, when should Claude use it, what does
             # a SKU look like in this system, is it read-only?
    {
        # TODO: "sku": str
    },
)
async def lookup_inventory(args: dict) -> dict:
    """
    TODO: call backend_lookup_inventory(args["sku"]) inside a try/except.

    On success, return:
        {"content": [{"type": "text", "text": <json.dumps of a useful payload>}]}

    On a caught InventoryError, DO NOT let it propagate - instead return:
        {"content": [{"type": "text", "text": f"Error: {e}"}], "is_error": True}

    This handler should NEVER raise - it's the boundary where a Python
    exception becomes a structured tool result the SDK can hand back to
    Claude. Crashing here is exactly the bug this exercise is about
    avoiding (see README.md 1.4).
    """
    raise NotImplementedError("TODO: implement lookup_inventory")


@tool(
    "create_order",
    "TODO",  # TODO: describe what this does, note that it DECREMENTS
             # stock (i.e. it's a mutating/consequential action, not a
             # read-only lookup), and when Claude should call it (e.g. only
             # once SKU/quantity/customer email are all confirmed, if
             # that's the behavior you want to encourage).
    {
        # TODO: "sku": str, "quantity": int, "customer_email": str
    },
)
async def create_order(args: dict) -> dict:
    """TODO: same pattern as lookup_inventory - call
    backend_create_order(**args) in a try/except, return a normal content
    result on success or an is_error result on InventoryError."""
    raise NotImplementedError("TODO: implement create_order")


@tool(
    "get_order_status",
    "TODO",  # TODO: describe what this does and what an order_id looks
             # like (see backend_create_order for the "ORD-####" format).
    {
        # TODO: "order_id": str
    },
)
async def get_order_status(args: dict) -> dict:
    """TODO: same pattern again - call backend_get_order_status(args["order_id"])."""
    raise NotImplementedError("TODO: implement get_order_status")


# ---------------------------------------------------------------------------
# PART B: SDK MCP SERVER + QUERY WIRING
# ---------------------------------------------------------------------------

# TODO: bundle the three tools into one in-process MCP server:
#
#     warehouse_server = create_sdk_mcp_server(
#         name="warehouse",
#         version="1.0.0",
#         tools=[lookup_inventory, create_order, get_order_status],
#     )
warehouse_server = None  # TODO

# TODO: build the options object. `allowed_tools` entries follow
# "mcp__<server_name>__<tool_name>" - the server_name here is "warehouse"
# (the `name=` you gave create_sdk_mcp_server above), NOT the module/file
# name.
#
#     options = ClaudeAgentOptions(
#         mcp_servers={"warehouse": warehouse_server},
#         allowed_tools=[
#             "mcp__warehouse__lookup_inventory",
#             "mcp__warehouse__create_order",
#             "mcp__warehouse__get_order_status",
#         ],
#     )
options = None  # TODO


async def run_agent(user_message: str) -> str:
    """
    TODO: run one query and return Claude's final text answer.

    1. final_text = ""
    2. async for message in query(prompt=user_message, options=options):
           if isinstance(message, AssistantMessage):
               for block in message.content:
                   if isinstance(block, TextBlock):
                       final_text = block.text
       (query() streams every message in the run - system messages, tool
       calls, tool results, assistant text turns, a final ResultMessage.
       Overwriting final_text each time you see one keeps the LAST assistant
       text block, which is what you want: Claude may "think out loud" or
       call tools across more than one assistant turn before it's done.)
    3. return final_text
    """
    raise NotImplementedError("TODO: implement run_agent")


# ---------------------------------------------------------------------------
# PART C: SCENARIOS
# ---------------------------------------------------------------------------

SCENARIOS = [
    (
        "How many units of SKU-100 do we have in stock?",
        # PREDICTION (fill in if you can't run this): expected tool call(s)
        # and outcome
    ),
    (
        "Please order 50 units of SKU-200 for customer alice@example.com.",
        # PREDICTION: SKU-200 only has 3 in stock (see MOCK_INVENTORY) -
        # this should trigger backend_create_order's insufficient-stock
        # InventoryError. Predict what a well-implemented handler lets
        # Claude do with that error instead of crashing.
    ),
    (
        "What's the status of order ORD-9999?",
        # PREDICTION: this order id was never created, so
        # backend_get_order_status should raise. Predict Claude's response.
    ),
]


async def main():
    for prompt, in [(s[0],) for s in SCENARIOS]:
        print(f"\n=== USER: {prompt} ===")
        try:
            answer = await run_agent(prompt)
            print("CLAUDE:", answer)
        except NotImplementedError as e:
            print(f"(not implemented yet: {e})")

    print(
        "\n=== ANSWER (fill in, 2-4 sentences) ===\n"
        "For the insufficient-stock scenario: what did Claude's final "
        "answer say once it received the structured error tool result? "
        "Then describe, concretely, what would have happened instead if "
        "the create_order handler had let the InventoryError propagate "
        "uncaught - what does the end user see in each case?"
    )


if __name__ == "__main__":
    asyncio.run(main())
